# Generated by Django 2.2.12 on 2020-05-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OldYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='Yönetim kurulunun başlangıç yılı:')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, verbose_name='Yönetim kurulundaki rol:')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=40, verbose_name='Yönetim kurulu üyesinin ismi:')),
                ('soyisim', models.CharField(max_length=40, verbose_name='Yönetim kurulu üyesinin soyismi:')),
                ('img', models.ImageField(upload_to='')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.Role', verbose_name='Yönetim kurulu üyesinin rolü:')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.OldYear', verbose_name='Yönetim kurulu üyesi hangi yıl görevdeydi.')),
            ],
            options={
                'ordering': ('isim', 'soyisim'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Danisman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=40, verbose_name='Yönetim kurulu üyesinin ismi:')),
                ('soyisim', models.CharField(max_length=40, verbose_name='Yönetim kurulu üyesinin soyismi:')),
                ('img', models.ImageField(upload_to='')),
                ('unvan', models.CharField(max_length=25, verbose_name='Kulüp danışmanının ünvanı:')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.OldYear', verbose_name='Kulüp danışmanının aktif olduğu yıl:')),
            ],
            options={
                'ordering': ('isim', 'soyisim'),
                'abstract': False,
            },
        ),
    ]
